const PDFDocument = require('pdfkit');

const COLORS = {
  navy: '#0F2419',
  teal: '#1B7A65',
  orange: '#E8711A',
  grey: '#666666',
  lightGrey: '#999999',
  border: '#E0E0E0',
};

function addHeader(doc, title, subtitle) {
  doc
    .rect(0, 0, doc.page.width, 90)
    .fill(COLORS.navy);

  doc
    .fillColor('#FFFFFF')
    .fontSize(20)
    .font('Helvetica-Bold')
    .text('IAMS', 40, 28);

  doc
    .fontSize(10)
    .font('Helvetica')
    .fillColor('#CFE3DC')
    .text('Industrial Attachment Management System', 40, 52);

  doc
    .fontSize(9)
    .fillColor('#CFE3DC')
    .text(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), 40, 68);

  doc.moveDown(3);
  doc.y = 110;

  doc
    .fillColor(COLORS.navy)
    .fontSize(16)
    .font('Helvetica-Bold')
    .text(title, 40, doc.y);

  if (subtitle) {
    doc
      .fontSize(10)
      .font('Helvetica')
      .fillColor(COLORS.grey)
      .text(subtitle, 40, doc.y + 4);
  }

  doc.moveDown(1.5);
  doc.moveTo(40, doc.y).lineTo(doc.page.width - 40, doc.y).strokeColor(COLORS.border).stroke();
  doc.moveDown(1);
}

function addTableRow(doc, columns, widths, opts = {}) {
  const startX = 40;
  const rowY = doc.y;
  const { bold = false, color = COLORS.navy, fontSize = 10 } = opts;

  doc.font(bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(fontSize).fillColor(color);

  let x = startX;
  columns.forEach((col, i) => {
    doc.text(String(col ?? '-'), x, rowY, { width: widths[i], ellipsis: true });
    x += widths[i];
  });

  doc.moveDown(0.8);
}

function addFooter(doc) {
  const range = doc.bufferedPageRange();
  for (let i = 0; i < range.count; i++) {
    doc.switchToPage(i);
    doc
      .fontSize(8)
      .fillColor(COLORS.lightGrey)
      .text(
        `Page ${i + 1} of ${range.count}  •  Generated by IAMS  •  Confidential`,
        40,
        doc.page.height - 40,
        { align: 'center', width: doc.page.width - 80 }
      );
  }
}

/**
 * students: [{ name, org, status, hours_worked, avg_score, completion_pct }]
 */
function generateStudentPerformancePDF(students, meta = {}) {
  const doc = new PDFDocument({ margin: 40, bufferPages: true, size: 'A4' });

  addHeader(
    doc,
    'Student Performance Summary',
    `${students.length} students  •  Supervisor: ${meta.supervisorName || '-'}`
  );

  const widths = [140, 110, 80, 70, 90];
  addTableRow(doc, ['Student', 'Organization', 'Status', 'Hours', 'Avg. Score'], widths, {
    bold: true,
    color: COLORS.teal,
    fontSize: 9,
  });
  doc.moveTo(40, doc.y).lineTo(doc.page.width - 40, doc.y).strokeColor(COLORS.border).stroke();
  doc.moveDown(0.5);

  students.forEach((s, idx) => {
    if (doc.y > doc.page.height - 100) {
      doc.addPage();
    }
    addTableRow(
      doc,
      [
        s.name,
        s.org || '-',
        s.status || '-',
        s.hours_worked != null ? `${s.hours_worked}h` : '-',
        s.avg_score != null ? `${s.avg_score}%` : '-',
      ],
      widths
    );
  });

  addFooter(doc);
  return doc;
}

/**
 * students: [{ name, submitted_count, expected_count, completion_pct, last_submission }]
 */
function generateLogbookCompletionPDF(students, meta = {}) {
  const doc = new PDFDocument({ margin: 40, bufferPages: true, size: 'A4' });

  addHeader(
    doc,
    'Logbook Completion Rate',
    `${students.length} students  •  Supervisor: ${meta.supervisorName || '-'}`
  );

  const widths = [160, 90, 90, 90];
  addTableRow(doc, ['Student', 'Submitted', 'Expected', 'Completion'], widths, {
    bold: true,
    color: COLORS.teal,
    fontSize: 9,
  });
  doc.moveTo(40, doc.y).lineTo(doc.page.width - 40, doc.y).strokeColor(COLORS.border).stroke();
  doc.moveDown(0.5);

  students.forEach((s) => {
    if (doc.y > doc.page.height - 100) {
      doc.addPage();
    }
    addTableRow(doc, [
      s.name,
      s.submitted_count,
      s.expected_count,
      `${s.completion_pct}%`,
    ], widths);
  });

  addFooter(doc);
  return doc;
}

/**
 * entries: [{ student_name, org, visit_date, rating, notes }]
 */
function generateHostOrgFeedbackPDF(entries, meta = {}) {
  const doc = new PDFDocument({ margin: 40, bufferPages: true, size: 'A4' });

  addHeader(
    doc,
    'Host Organization Feedback',
    `${entries.length} entries  •  Supervisor: ${meta.supervisorName || '-'}`
  );

  entries.forEach((e) => {
    if (doc.y > doc.page.height - 140) {
      doc.addPage();
    }
    doc
      .font('Helvetica-Bold')
      .fontSize(11)
      .fillColor(COLORS.navy)
      .text(`${e.student_name}  —  ${e.org || 'Unknown Organization'}`, 40, doc.y);

    doc
      .font('Helvetica')
      .fontSize(9)
      .fillColor(COLORS.lightGrey)
      .text(
        `${e.visit_date ? new Date(e.visit_date).toLocaleDateString() : '-'}${
          e.rating != null ? `   •   Rating: ${e.rating}/5` : ''
        }`,
        40,
        doc.y + 2
      );

    doc.moveDown(0.4);
    doc
      .font('Helvetica')
      .fontSize(10)
      .fillColor(COLORS.grey)
      .text(e.notes || 'No notes provided.', 40, doc.y, { width: doc.page.width - 80 });

    doc.moveDown(1);
    doc.moveTo(40, doc.y).lineTo(doc.page.width - 40, doc.y).strokeColor(COLORS.border).stroke();
    doc.moveDown(1);
  });

  addFooter(doc);
  return doc;
}

module.exports = {
  generateStudentPerformancePDF,
  generateLogbookCompletionPDF,
  generateHostOrgFeedbackPDF,
};