const PDFDocument = require('pdfkit');

const COLORS = {
  navy: '#0F2419',
  teal: '#1B7A65',
  orange: '#E8711A',
  grey: '#666666',
  lightGrey: '#999999',
  border: '#E0E0E0',
};

function addHeader(doc, title, subtitle) {
  doc
    .rect(0, 0, doc.page.width, 90)
    .fill(COLORS.navy);

  doc
    .fillColor('#FFFFFF')
    .fontSize(20)
    .font('Helvetica-Bold')
    .text('IAMS', 40, 28);

  doc
    .fontSize(10)
    .font('Helvetica')
    .fillColor('#CFE3DC')
    .text('Industrial Attachment Management System', 40, 52);

  doc
    .fontSize(9)
    .fillColor('#CFE3DC')
    .text(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), 40, 68);

  doc.moveDown(3);
  doc.y = 110;

  doc
    .fillColor(COLORS.navy)
    .fontSize(16)
    .font('Helvetica-Bold')
    .text(title, 40, doc.y);

  if (subtitle) {
    doc
      .fontSize(10)
      .font('Helvetica')
      .fillColor(COLORS.grey)
      .text(subtitle, 40, doc.y + 4);
  }

  doc.moveDown(1.5);
  doc.moveTo(40, doc.y).lineTo(doc.page.width - 40, doc.y).strokeColor(COLORS.border).stroke();
  doc.moveDown(1);
}

function addTableRow(doc, columns, widths, opts = {}) {
  const startX = 40;
  const rowY = doc.y;
  const { bold = false, color = COLORS.navy, fontSize = 10 } = opts;

  doc.font(bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(fontSize).fillColor(color);

  let x = startX;
  columns.forEach((col, i) => {
    doc.text(String(col ?? '-'), x, rowY, { width: widths[i], ellipsis: true });
    x += widths[i];
  });

  doc.moveDown(0.8);
}

function addFooter(doc) {
  const range = doc.bufferedPageRange();
  for (let i = 0; i < range.count; i++) {
    doc.switchToPage(i);
    doc
      .fontSize(8)
      .fillColor(COLORS.lightGrey)
      .text(
        `Page ${i + 1} of ${range.count}  •  Generated by IAMS  •  Confidential`,
        40,
        doc.page.height - 40,
        { align: 'center', width: doc.page.width - 80 }
      );
  }
}

/**
 * students: [{ name, org, status, hours_worked, avg_score, completion_pct }]
 */
function generateStudentPerformancePDF(students, meta = {}) {
  const doc = new PDFDocument({ margin: 40, bufferPages: true, size: 'A4' });

  addHeader(
    doc,
    'Student Performance Summary',
    `${students.length} students  •  Supervisor: ${meta.supervisorName || '-'}`
  );

  const widths = [140, 110, 80, 70, 90];
  addTableRow(doc, ['Student', 'Organization', 'Status', 'Hours', 'Avg. Score'], widths, {
    bold: true,
    color: COLORS.teal,
    fontSize: 9,
  });
  doc.moveTo(40, doc.y).lineTo(doc.page.width - 40, doc.y).strokeColor(COLORS.border).stroke();
  doc.moveDown(0.5);

  students.forEach((s, idx) => {
    if (doc.y > doc.page.height - 100) {
      doc.addPage();
    }
    addTableRow(
      doc,
      [
        s.name,
        s.org || '-',
        s.status || '-',
        s.hours_worked != null ? `${s.hours_worked}h` : '-',
        s.avg_score != null ? `${s.avg_score}%` : '-',
      ],
      widths
    );
  });

  addFooter(doc);
  return doc;
}

/**
 * students: [{ name, submitted_count, expected_count, completion_pct, last_submission }]
 */
function generateLogbookCompletionPDF(students, meta = {}) {
  const doc = new PDFDocument({ margin: 40, bufferPages: true, size: 'A4' });

  addHeader(
    doc,
    'Logbook Completion Rate',
    `${students.length} students  •  Supervisor: ${meta.supervisorName || '-'}`
  );

  const widths = [160, 90, 90, 90];
  addTableRow(doc, ['Student', 'Submitted', 'Expected', 'Completion'], widths, {
    bold: true,
    color: COLORS.teal,
    fontSize: 9,
  });
  doc.moveTo(40, doc.y).lineTo(doc.page.width - 40, doc.y).strokeColor(COLORS.border).stroke();
  doc.moveDown(0.5);

  students.forEach((s) => {
    if (doc.y > doc.page.height - 100) {
      doc.addPage();
    }
    addTableRow(doc, [
      s.name,
      s.submitted_count,
      s.expected_count,
      `${s.completion_pct}%`,
    ], widths);
  });

  addFooter(doc);
  return doc;
}

/**
 * entries: [{ student_name, org, visit_date, rating, notes }]
 * NOTE: this now sources from `evaluations` (score is a 0-100 percentage,
 * matching the notification text in POST /evaluations), not site_visits'
 * old /5 rating — hence "Score: X%" below instead of "Rating: X/5".
 */
function generateHostOrgFeedbackPDF(entries, meta = {}) {
  const doc = new PDFDocument({ margin: 40, bufferPages: true, size: 'A4' });

  addHeader(
    doc,
    'Host Organization Feedback',
    `${entries.length} entries  •  Supervisor: ${meta.supervisorName || '-'}`
  );

  entries.forEach((e) => {
    if (doc.y > doc.page.height - 140) {
      doc.addPage();
    }
    doc
      .font('Helvetica-Bold')
      .fontSize(11)
      .fillColor(COLORS.navy)
      .text(`${e.student_name}  —  ${e.org || 'Unknown Organization'}`, 40, doc.y);

    doc
      .font('Helvetica')
      .fontSize(9)
      .fillColor(COLORS.lightGrey)
      .text(
        `${e.visit_date ? new Date(e.visit_date).toLocaleDateString() : '-'}${
          e.rating != null ? `   •   Score: ${e.rating}%` : ''
        }`,
        40,
        doc.y + 2
      );

    doc.moveDown(0.4);
    doc
      .font('Helvetica')
      .fontSize(10)
      .fillColor(COLORS.grey)
      .text(e.notes || 'No notes provided.', 40, doc.y, { width: doc.page.width - 80 });

    doc.moveDown(1);
    doc.moveTo(40, doc.y).lineTo(doc.page.width - 40, doc.y).strokeColor(COLORS.border).stroke();
    doc.moveDown(1);
  });

  addFooter(doc);
  return doc;
}

function generateAdminSummaryPDF(summary, meta = {}) {
  const doc = new PDFDocument({ margin: 40, bufferPages: true, size: 'A4' });

  addHeader(doc, 'System Summary Report', `Generated by ${meta.adminName || 'Admin'}`);

  const totals = [
    ['Total Placements', summary.totalAttachments],
    ['Active Students', summary.totalStudents],
    ['Supervisors', summary.totalSupervisors],
    ['Partner Organizations', summary.totalOrgs],
  ];
  const totalsWidths = [220, 100];
  totals.forEach(([label, value]) => {
    addTableRow(doc, [label, value ?? 0], totalsWidths, { bold: true, fontSize: 11 });
  });
  doc.moveDown(0.5);
  doc.moveTo(40, doc.y).lineTo(doc.page.width - 40, doc.y).strokeColor(COLORS.border).stroke();
  doc.moveDown(1);

  const section = (title, rows, columns, widths) => {
    if (doc.y > doc.page.height - 160) doc.addPage();
    doc.font('Helvetica-Bold').fontSize(13).fillColor(COLORS.navy).text(title, 40, doc.y);
    doc.moveDown(0.6);
    addTableRow(doc, columns, widths, { bold: true, color: COLORS.teal, fontSize: 9 });
    doc.moveTo(40, doc.y).lineTo(doc.page.width - 40, doc.y).strokeColor(COLORS.border).stroke();
    doc.moveDown(0.4);
    rows.forEach((r) => {
      if (doc.y > doc.page.height - 100) doc.addPage();
      addTableRow(doc, r, widths);
    });
    doc.moveDown(1);
  };

  section(
    'Status Breakdown',
    (summary.statusBreakdown || []).map(s => [s.status, s.count]),
    ['Status', 'Count'],
    [220, 100]
  );

  section(
    'Top Organizations',
    (summary.orgBreakdown || []).map(o => [o.org_name, o.count]),
    ['Organization', 'Placements'],
    [220, 100]
  );

  section(
    'Department Breakdown',
    (summary.deptBreakdown || []).map(d => [d.department, d.count]),
    ['Department', 'Placements'],
    [220, 100]
  );

  addFooter(doc);
  return doc;
}

/**
 * attachment: single attachment record with joined student/org/supervisor fields
 * logbookEntries: [{ week_number, description, tasks_done, challenges, submitted_at }]
 * evaluation: { rating, comments, supervisor_name } | null
 */
function generateAttachmentReportPDF(attachment, logbookEntries = [], evaluation = null) {
  const doc = new PDFDocument({ margin: 40, bufferPages: true, size: 'A4' });

  addHeader(
    doc,
    'Attachment Report',
    `${attachment.student_name || 'Unknown Student'}  •  Reg: ${attachment.reg_number || '-'}`
  );

  const infoRows = [
    ['Department', attachment.department || '-'],
    ['Organization', attachment.org_name || '-'],
    ['Location', attachment.location || '-'],
    ['Supervisor', attachment.supervisor_name || 'Not assigned'],
    ['Status', (attachment.status || '-').toUpperCase()],
    ['Start Date', attachment.start_date ? new Date(attachment.start_date).toLocaleDateString() : '-'],
    ['End Date', attachment.end_date ? new Date(attachment.end_date).toLocaleDateString() : '-'],
  ];
  const infoWidths = [140, 320];
  infoRows.forEach(([label, value]) => {
    addTableRow(doc, [label, value], infoWidths, { bold: true, fontSize: 10 });
  });
  doc.moveDown(0.5);
  doc.moveTo(40, doc.y).lineTo(doc.page.width - 40, doc.y).strokeColor(COLORS.border).stroke();
  doc.moveDown(1);

  // Logbook entries
  if (doc.y > doc.page.height - 160) doc.addPage();
  doc.font('Helvetica-Bold').fontSize(13).fillColor(COLORS.navy).text('Logbook Entries', 40, doc.y);
  doc.moveDown(0.6);

  if (!logbookEntries.length) {
    doc.font('Helvetica').fontSize(10).fillColor(COLORS.lightGrey).text('No logbook entries submitted.', 40, doc.y);
    doc.moveDown(1);
  } else {
    logbookEntries.forEach((e) => {
      if (doc.y > doc.page.height - 140) doc.addPage();
      doc
        .font('Helvetica-Bold').fontSize(11).fillColor(COLORS.navy)
        .text(`Week ${e.week_number ?? '-'}`, 40, doc.y);
      doc
        .font('Helvetica').fontSize(9).fillColor(COLORS.lightGrey)
        .text(e.submitted_at ? `Submitted: ${new Date(e.submitted_at).toLocaleDateString()}` : 'Not submitted', 40, doc.y + 2);
      doc.moveDown(0.4);
      doc
        .font('Helvetica').fontSize(10).fillColor(COLORS.grey)
        .text(e.tasks_done || e.description || 'No details provided.', 40, doc.y, { width: doc.page.width - 80 });
      if (e.challenges) {
        doc.moveDown(0.2);
        doc
          .font('Helvetica-Oblique').fontSize(9).fillColor(COLORS.lightGrey)
          .text(`Challenges: ${e.challenges}`, 40, doc.y, { width: doc.page.width - 80 });
      }
      doc.moveDown(0.8);
      doc.moveTo(40, doc.y).lineTo(doc.page.width - 40, doc.y).strokeColor(COLORS.border).stroke();
      doc.moveDown(0.8);
    });
  }

  // Evaluation
  if (doc.y > doc.page.height - 140) doc.addPage();
  doc.font('Helvetica-Bold').fontSize(13).fillColor(COLORS.navy).text('Evaluation', 40, doc.y);
  doc.moveDown(0.6);

  if (!evaluation) {
    doc.font('Helvetica').fontSize(10).fillColor(COLORS.lightGrey).text('No evaluation submitted yet.', 40, doc.y);
  } else {
    doc
      .font('Helvetica-Bold').fontSize(10).fillColor(COLORS.navy)
      .text(`Rating: ${evaluation.rating != null ? `${evaluation.rating}/5` : '-'}`, 40, doc.y);
    doc
      .font('Helvetica').fontSize(9).fillColor(COLORS.lightGrey)
      .text(`Evaluated by: ${evaluation.supervisor_name || '-'}`, 40, doc.y + 2);
    if (evaluation.comments) {
      doc.moveDown(0.5);
      doc
        .font('Helvetica').fontSize(10).fillColor(COLORS.grey)
        .text(evaluation.comments, 40, doc.y, { width: doc.page.width - 80 });
    }
  }

  addFooter(doc);
  return doc;
}

module.exports = {
  generateStudentPerformancePDF,
  generateLogbookCompletionPDF,
  generateHostOrgFeedbackPDF,
  generateAdminSummaryPDF,
  generateAttachmentReportPDF,
};